django:
  secret_key: ???

db:
  name: ???
  user: ???
  password: ???
  host: ???

email:
  use_tls: yes
  host: ???
  host_user: ???@???
  host_password: ???
  port: ???

social:
  github:
    key: ???
    secret: ???

moesif:
  application_id: ???